services:
  db:
    container_name: mobile-order-postgres-0
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345godislove
      POSTGRES_DB: directus
    ports:
      - "5432:5432"
    volumes:
      - "mobile-order-db:/var/lib/postgresql"

  cms:
    container_name: mobile-order-directus-0
    image: directus/directus:latest
    environment:
      DB_CLIENT: pg
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: directus
      DB_USER: postgres
      DB_PASSWORD: 12345godislove
      SECRET: hf09wuy043h09hf0ih90h2bwe88g3g9wkudghv3ug83
      PUBLIC_URL: http://0.0.0.0:8055
    ports:
      - "8055:8055"

volumes:
  mobile-order-db: