ktor:
  deployment:
    port: 8080
  application:
    modules:
      - one.nfolio.MainKt.module
    route-path: https://mac.nfolio.one/

directus:
  host: localhost
  port: 8055
  access-token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

HMAC:
  secret-key: xxxxxxxxxxxxxxxxxxxx

LIFF:
  id: xxxxxxxxxx
