[versions]
kotlin = "2.4.10"
logback = "1.5.34"
ktlint = "14.2.0"
loki4j = "2.1.0"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
loki4j = { module = "com.github.loki4j:loki-logback-appender", version.ref = "loki4j" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
